name: hello-world
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1    
    - run: make setup
    - run: make install
    - run: make build
    - run: make lint
    - name: run tests
      run: make test
   