name: set_up
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        npm-version: 6
    - run: make setup
    - name: run tests
      run: make test
      run: make lint